// Mock data for the veterinary symptom matching dashboard
// Corrected with actual project data (run_matching.py 결과 기준)

window.APP_DATA = {
  stats: {
    total: 21604,
    train: 19205,
    val: 2399,
    depts: 5,
  },
  lifecycle: [
    { key: "puppy",  ko: "자견",   en: "Puppy",  count: 7160 },
    { key: "adult",  ko: "성견",   en: "Adult",  count: 7275 },
    { key: "senior", ko: "노령견", en: "Senior", count: 7169 },
  ],
  department: [
    { key: "internal", ko: "내과",   en: "Internal",      pct: 51, color: "var(--accent)"   },
    { key: "surgery",  ko: "외과",   en: "Surgery",        pct: 27, color: "var(--accent-2)" },
    { key: "derm",     ko: "피부과", en: "Dermatology",    pct: 13, color: "var(--accent-3)" },
    { key: "ophth",    ko: "안과",   en: "Ophthalmology",  pct: 5,  color: "var(--accent-4)" },
    { key: "dental",   ko: "치과",   en: "Dental",         pct: 4,  color: "var(--accent-5)" },
  ],
  // ✅ 실제 AI Hub 데이터 기준 Top 15
  diseaseTop: [
    { name: "기타",           en: "Other",                       count: 16611 },
    { name: "중성화수술",     en: "Neutering",                   count: 642   },
    { name: "무릎뼈 탈구",   en: "Patellar luxation",            count: 593   },
    { name: "중독",           en: "Poisoning",                   count: 473   },
    { name: "골절",           en: "Fracture",                    count: 408   },
    { name: "심장사상충",     en: "Heartworm",                   count: 396   },
    { name: "자궁축농증",     en: "Pyometra",                    count: 367   },
    { name: "외이염",         en: "Otitis externa",              count: 326   },
    { name: "위장관폐색",     en: "GI obstruction",              count: 256   },
    { name: "아토피성 피부염",en: "Atopic dermatitis",           count: 248   },
    { name: "방광염",         en: "Cystitis",                    count: 228   },
    { name: "결막염",         en: "Conjunctivitis",              count: 152   },
    { name: "부신피질기능항진증", en: "Hyperadrenocorticism",    count: 129   },
    { name: "제3안검탈출증",  en: "Third eyelid prolapse",       count: 108   },
    { name: "유루증",         en: "Epiphora",                    count: 89    },
  ],
  textLen: {
    q: { mean: 329, median: 258, max: 3208 },
    a: { mean: 394, median: 317, max: 3707 },
  },
  metrics: {
    overall: [
      { k: "Hit@1", tfidf: 16.0,  bert: 24.0  },
      { k: "Hit@3", tfidf: 40.0,  bert: 52.0  },
      { k: "Hit@5", tfidf: 52.0,  bert: 62.0  },
      { k: "MAP@5", tfidf: 9.35,  bert: 12.87 },
    ],
    byLifecycle: [
      { key: "puppy",  ko: "자견",   n: 17, tfidf: 70.6, bert: 82.4 },
      { key: "adult",  ko: "성견",   n: 17, tfidf: 47.1, bert: 41.2 },
      { key: "senior", ko: "노령견", n: 16, tfidf: 37.5, bert: 62.5 },
    ],
  },
  exampleQuery: "강아지가 밥을 안 먹고 자꾸 토해요. 3일째 기운이 없어요.",
  sampleSuggestions: [
    "눈에 눈곱이 자꾸 끼고 빨갛게 충혈돼요",
    "산책 후 뒷다리를 절뚝거려요",
    "귀를 자주 긁고 냄새가 나요",
    "피부에 붉은 발진이 생겼어요",
    "물을 너무 많이 마시고 소변을 자주 봐요",
  ],
  results: {
    bert: [
      {
        rank: 1, sim: 0.8421, lifecycle: "성견", dept: "내과", disease: "위장염",
        q: "5살 말티즈가 어제부터 사료를 거부하고 노란 액체를 3번 토했습니다. 물만 조금 마시고 하루 종일 엎드려 있어요. 병원에 가야 할까요?",
        a: "3일 이상 식욕부진과 구토가 지속되면 탈수·췌장염·이물 섭취를 의심해야 합니다. 특히 노란 위액 구토와 기력 저하가 동반된 경우 가능한 빨리 내원하여 혈액검사와 복부 방사선 촬영을 권장드립니다.",
      },
      {
        rank: 2, sim: 0.8156, lifecycle: "성견", dept: "내과", disease: "췌장염",
        q: "강아지가 이틀째 아무것도 안 먹고 토하기만 해요. 배를 만지면 아파하는 것 같습니다.",
        a: "복부 촉진 시 통증 반응은 췌장염의 전형적인 신호입니다. cPL 검사와 복부 초음파가 필요하며, 확진 시 수액 치료·금식·진통 관리가 원칙입니다.",
      },
      {
        rank: 3, sim: 0.7934, lifecycle: "성견", dept: "내과", disease: "기타",
        q: "7살 포메라니안이 밥을 조금씩만 먹고 구토가 반복됩니다. 체중이 빠지는 것 같아요.",
        a: "만성적인 식욕부진과 체중 감소는 내분비 질환, 만성 신장질환, 종양을 배제해야 하는 증상입니다. 전혈검사와 호르몬 검사를 권합니다.",
      },
      {
        rank: 4, sim: 0.7712, lifecycle: "노령견", dept: "내과", disease: "신장질환",
        q: "노견이 최근 물을 많이 마시고 사료를 남깁니다. 가끔 노란 거품을 토해요.",
        a: "다음다뇨(PU/PD)와 식욕부진은 신장 기능 저하의 초기 신호일 수 있습니다. BUN/Crea, SDMA, 요비중 검사가 우선되어야 합니다.",
      },
      {
        rank: 5, sim: 0.7488, lifecycle: "성견", dept: "내과", disease: "위장염",
        q: "이물질을 먹은 것 같은데 식욕이 없고 구토를 합니다.",
        a: "이물 섭취가 의심된다면 구토 유도는 위험할 수 있으므로 먼저 방사선 검사로 위치를 확인해야 합니다.",
      },
    ],
    tfidf: [
      {
        rank: 1, sim: 0.6712, lifecycle: "성견", dept: "내과", disease: "기타",
        q: "강아지가 기운이 없고 밥을 안 먹습니다. 산책도 싫어해요.",
        a: "무기력과 식욕부진은 매우 비특이적 증상으로, 감염성 질환부터 내분비·종양까지 폭넓은 감별이 필요합니다.",
      },
      {
        rank: 2, sim: 0.6341, lifecycle: "자견", dept: "내과", disease: "파보바이러스",
        q: "강아지가 토하고 설사도 해요. 3개월된 자견입니다.",
        a: "3개월령 자견에서 구토·혈변·식욕부진은 파보바이러스 감염을 반드시 배제해야 합니다.",
      },
      {
        rank: 3, sim: 0.6108, lifecycle: "성견", dept: "내과", disease: "위장염",
        q: "강아지 토하고 기운 없어요",
        a: "단순 위장염인지 구별하기 위해 다른 증상의 동반 여부를 확인하세요. 12시간 금식 후 처방 사료 소량 급여로 호전되지 않으면 내원이 필요합니다.",
      },
      {
        rank: 4, sim: 0.5893, lifecycle: "성견", dept: "외과", disease: "이물 섭취",
        q: "강아지가 양말을 삼킨 것 같아요. 토를 계속 해요.",
        a: "선형 이물은 장 주름 사이에 걸려 장중첩을 일으킬 수 있어 매우 위험합니다. 즉시 방사선 검사가 필요합니다.",
      },
      {
        rank: 5, sim: 0.5624, lifecycle: "노령견", dept: "내과", disease: "기타",
        q: "나이든 강아지가 며칠째 밥을 못 먹어요.",
        a: "노령견의 장기간 식욕부진은 치아·구강 통증, 만성 질환, 종양 등 원인이 다양합니다.",
      },
    ],
  },
  // ✅ 실제 Ground Truth 50개 쿼리
  evalQueries: [
    { id: "Q001", life: "자견",   dept: "내과",   disease: "기타",              title: "예방접종을 어린 시절에 실시하여 6년 동안 건강하게 지내고 있는데, 정기적으로 추가 접종을 해야 하는지 여쭤봅니다." },
    { id: "Q002", life: "자견",   dept: "내과",   disease: "기타",              title: "강아지가 이물질을 섭취한 것 같은데, 장내에서 배출되는지 판단하기가 어렵습니다." },
    { id: "Q003", life: "자견",   dept: "내과",   disease: "기타",              title: "중성화한 10세 포메라니안이 어제부터 빈번하게 무른 배변을 봅니다." },
    { id: "Q004", life: "자견",   dept: "내과",   disease: "기타",              title: "강아지가 기침을 계속하고 콧물도 멈추지 않은 지 꽤 오래됐어요." },
    { id: "Q005", life: "자견",   dept: "외과",   disease: "자궁축농증",        title: "3세 암컷 포메라니안이 생리 후에도 분비물이 계속 나와요." },
    { id: "Q006", life: "자견",   dept: "내과",   disease: "기타",              title: "오늘 강아지가 검게 변한 설사를 보았습니다. 접종은 1차만 맞은 상태예요." },
    { id: "Q007", life: "자견",   dept: "피부과", disease: "외이염",            title: "강아지 귀에 검은색 딱지가 있어요. 닦으려고 하면 아파해요." },
    { id: "Q008", life: "자견",   dept: "내과",   disease: "기타",              title: "반려견 코코가 만성적인 구토 증상을 나타내고 있어요." },
    { id: "Q009", life: "자견",   dept: "내과",   disease: "기타",              title: "강아지가 잠을 자다가 숨쉬기 힘들어하는 모습을 보여요. 현재 13세입니다." },
    { id: "Q010", life: "자견",   dept: "내과",   disease: "기타",              title: "3살 중형견에게 애견 통조림이나 고기를 급여해도 될까요?" },
    { id: "Q011", life: "자견",   dept: "외과",   disease: "중성화수술",        title: "5살 암컷 강아지 중성화 수술을 고민 중인데, 안 하면 어떤 질병이 생기나요?" },
    { id: "Q012", life: "자견",   dept: "치과",   disease: "기타",              title: "4개월 된 푸들의 유치가 빠지고 영구치가 나고 있어요." },
    { id: "Q013", life: "자견",   dept: "내과",   disease: "급성신부전",        title: "강아지가 포도껍질을 먹었어요. 어제부터 오늘까지 괜찮은 것 같은데 걱정됩니다." },
    { id: "Q014", life: "자견",   dept: "안과",   disease: "기타",              title: "강아지가 다음 주 내안각 수술을 받을 예정인데 마취가 걱정돼요." },
    { id: "Q015", life: "자견",   dept: "치과",   disease: "기타",              title: "갑자기 강아지 입에서 비릿한 피냄새가 나기 시작했습니다." },
    { id: "Q016", life: "자견",   dept: "외과",   disease: "무릎뼈 탈구",      title: "강아지에게 비장종양, 슬개골 탈구 3기, 디스크 증상이 확인됐어요." },
    { id: "Q017", life: "자견",   dept: "내과",   disease: "기타",              title: "반려견 심장이 일반 개보다 두세 배 빠르게 뛰는 것 같아요." },
    { id: "Q018", life: "성견",   dept: "피부과", disease: "기타",              title: "포메라니안 피부 상태가 갑자기 심하게 악화됐어요." },
    { id: "Q019", life: "성견",   dept: "내과",   disease: "위장관폐색",        title: "리트리버가 아이스크림을 먹었는데 이상한 행동을 보이고 있어요." },
    { id: "Q020", life: "성견",   dept: "내과",   disease: "기타",              title: "10살 말티즈가 지난 3월부터 급격히 야위어가고 있어요." },
    { id: "Q021", life: "성견",   dept: "내과",   disease: "기타",              title: "강아지가 물을 과도하게 마시고 있습니다. 한 번에 다 마셔버려요." },
    { id: "Q022", life: "성견",   dept: "내과",   disease: "중독",              title: "5개월 비글이 포도를 섭취했어요. 어떻게 해야 하나요?" },
    { id: "Q023", life: "성견",   dept: "치과",   disease: "치은염",            title: "12개월 골든 리트리버 잇몸에 작은 혹이 몇 달째 있어요." },
    { id: "Q024", life: "성견",   dept: "외과",   disease: "기타",              title: "10세 강아지 슬개골 탈구 수술 후 회복 관리에 대해 궁금합니다." },
    { id: "Q025", life: "성견",   dept: "내과",   disease: "기타",              title: "강아지가 최근 숨을 조금 더 빠르게 쉬는 것 같아요." },
    { id: "Q026", life: "성견",   dept: "내과",   disease: "위장관폐색",        title: "강아지가 목에 무언가 걸린 듯 켁켁거리며 기침을 해요." },
    { id: "Q027", life: "성견",   dept: "내과",   disease: "기타",              title: "6세 시바견이 계단에서 떨어진 뒤 이상한 행동을 보여요." },
    { id: "Q028", life: "성견",   dept: "외과",   disease: "기타",              title: "11세 강아지 항문 주변에 혹이 생겼어요." },
    { id: "Q029", life: "성견",   dept: "내과",   disease: "기타",              title: "산에 다녀온 후 진드기에 물린 것 같아요. 어떻게 해야 하나요?" },
    { id: "Q030", life: "성견",   dept: "내과",   disease: "기타",              title: "17세 말티즈가 간식 후 일시적으로 기침이 심해져요." },
    { id: "Q031", life: "성견",   dept: "치과",   disease: "기타",              title: "노견 입냄새가 매우 심각합니다. 껌을 줘도 소용없어요." },
    { id: "Q032", life: "성견",   dept: "안과",   disease: "기타",              title: "강아지 눈이 뿌옇게 변한 것 같은데 백내장일까요?" },
    { id: "Q033", life: "성견",   dept: "내과",   disease: "기타",              title: "반려견 오줌에서 검고 날카로운 이물질이 발견됐어요." },
    { id: "Q034", life: "성견",   dept: "내과",   disease: "기타",              title: "2년 7개월 포메라니안 3.5kg, 건강검진을 어떻게 받아야 하나요?" },
    { id: "Q035", life: "노령견", dept: "피부과", disease: "외이염",            title: "강아지가 갑자기 귀를 지속적으로 긁어요. 매우 염려됩니다." },
    { id: "Q036", life: "노령견", dept: "내과",   disease: "기타",              title: "12세 강아지가 갑자기 경련을 일으키고 쓰러졌어요." },
    { id: "Q037", life: "노령견", dept: "외과",   disease: "기타",              title: "어릴 때부터 슬개골 탈구였는데 최근 3기로 진단받아 수술을 권유받았어요." },
    { id: "Q038", life: "노령견", dept: "내과",   disease: "기타",              title: "2세 수컷 스피츠가 최근 이전과 다른 행동을 보여요." },
    { id: "Q039", life: "노령견", dept: "내과",   disease: "기타",              title: "강아지 몸에서 나오는 액체가 오줌인지 자궁 분비물인지 모르겠어요." },
    { id: "Q040", life: "노령견", dept: "치과",   disease: "기타",              title: "강아지 송곳니 위치에 이빨이 2개인 것 같아요." },
    { id: "Q041", life: "노령견", dept: "외과",   disease: "자궁축농증",        title: "중성화 수술이 반드시 필요한지, 위험은 없는지 궁금합니다." },
    { id: "Q042", life: "노령견", dept: "내과",   disease: "기타",              title: "13살 된 시츄 노령견 건강 관리 어떻게 하면 좋을까요?" },
    { id: "Q043", life: "노령견", dept: "내과",   disease: "기타",              title: "강아지가 몸을 떨고 불안하게 돌아다니며 팔을 뻗는 자세를 취해요." },
    { id: "Q044", life: "노령견", dept: "내과",   disease: "기타",              title: "4개월 비숑 프리제 2kg, 아직 중성화하지 않았는데 적당한 시기가 언제인가요?" },
    { id: "Q045", life: "노령견", dept: "외과",   disease: "기타",              title: "1년 6개월 말티즈 1.4kg이 문에 부딪혀 다리를 다쳤어요." },
    { id: "Q046", life: "노령견", dept: "내과",   disease: "기타",              title: "강아지 체중이 11kg인데 적정 체중 7kg보다 너무 많이 나가요." },
    { id: "Q047", life: "노령견", dept: "내과",   disease: "부신피질기능항진증", title: "강아지가 쿠싱증후군인지 궁금합니다. 피부가 이상하고 배가 부풀어 있어요." },
    { id: "Q048", life: "노령견", dept: "치과",   disease: "기타",              title: "강아지 치아에 통증이 생기면 어떻게 표현하나요? 발치가 필요한지 궁금해요." },
    { id: "Q049", life: "노령견", dept: "안과",   disease: "결막염",            title: "강아지 눈꺼풀에 이상한 것이 생겼어요. 눈을 자꾸 비벼요." },
    { id: "Q050", life: "노령견", dept: "내과",   disease: "기타",              title: "요즘 개들의 평균 수명이 얼마나 되나요? 노령견 건강 관리가 궁금합니다." },
  ],
};
